// src/renderer/src/views/account/index.vue
<script setup>
import { ref, onMounted } from 'vue'
import {api} from '../../api/http'
const accounts = ref([])

async function getAccounts(page=1, size=10){
  try{
    const res = await api.get('/accounts')
    console.log(res)
    accounts.value = res.data.accounts
  }catch(error){
    console.error(error)
  }
}



onMounted(()=>{
  getAccounts()
})
</script>

<template>
  <div>
    <div style="margin-top: 12px;">
      <el-table :data="accounts" border>
        <el-table-column prop="id" label="编号" width="100"></el-table-column>
        <el-table-column prop="phone" label="名称"></el-table-column>
        <el-table-column prop="path" label="路径" show-overflow-tooltip></el-table-column>
        <el-table-column prop="is_banned" label="是否失效"></el-table-column>
        <el-table-column prop="in_use" label="使用状态"></el-table-column>
        <el-table-column prop="limit_until" label="限制解除时间" show-overflow-tooltip></el-table-column>
        <el-table-column prop="last_used_at" label="上次使用" show-overflow-tooltip></el-table-column>
        <el-table-column prop="channels_count" label="频道数量"></el-table-column>
        <el-table-column prop="operations" label="操作">
          <template #default="scope">
            <el-space>
              <el-button size="small" type="danger">删除</el-button>
            </el-space>
          </template>
        </el-table-column>
      </el-table>
    </div>
  </div>
</template>

// src/renderer/src/pages/Account/index.jsx
import { useState, useEffect } from 'react'
import { Table, Button } from 'antd'
import api from '@renderer/api/http'
import { localFTime } from '@renderer/utils/tools'

import PageView from '../../components/PageView'
export default function Account() {
    const [accounts, setAccounts] = useState([])
    const columns = [
        { title: '编号', dataIndex: 'id' },
        { title: '名称', dataIndex: 'phone', ellipsis: true },
        { title: '路径', dataIndex: 'path', ellipsis: true },
        {
            title: '冻结',
            dataIndex: 'is_banned',
            render: (value) => (value === 1 ? '是' : '否')
        },
        {
            title: '临时',
            dataIndex: 'is_tmp',
            render: (value) => (value === 1 ? '是' : '否')
        },
        {
            title: '限制时间',
            dataIndex: 'limited_until',
            render: (value) => (value ? localFTime(value) : '-')
        },
        { title: '频道数量', dataIndex: 'channels_count' },
        {
            title: '上次使用',
            dataIndex: 'last_used_at',
            render: (value) => localFTime(value)
        },
        {
            title: '操作',
            fixed: 'right',
            width: 200,
            render: (_, record) => (
                <>
                    <Button type="primary" size="small">
                        临时客户端
                    </Button>
                </>
            )
        }
    ]

    async function getAccounts(page = 1, size = 10) {
        try {
            const res = await api.get(`/accounts?page=${page}&size=${size}`)
            if (res.code === 200) {
                const data = res.data.accounts
                setAccounts(data)
            }
        } catch (error) {
            console.error(error)
        }
    }

    useEffect(() => {
        getAccounts()
    })
    return (
        <>
            <PageView>
                <Table
                    columns={columns}
                    dataSource={accounts}
                    rowKey="id"
                    bordered
                    scroll={{ x: 'max-content' }}
                />
            </PageView>
        </>
    )
}
